// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: free_go/gunk/v1/allData/all.proto

package allData

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{0}
}

func (x *Name) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Name) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Name `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *CreateNameRequest) Reset() {
	*x = CreateNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNameRequest) ProtoMessage() {}

func (x *CreateNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNameRequest.ProtoReflect.Descriptor instead.
func (*CreateNameRequest) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNameRequest) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

type CreateNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CreateNameResponse) Reset() {
	*x = CreateNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNameResponse) ProtoMessage() {}

func (x *CreateNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNameResponse.ProtoReflect.Descriptor instead.
func (*CreateNameResponse) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNameResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetNameRequest) Reset() {
	*x = GetNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameRequest) ProtoMessage() {}

func (x *GetNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameRequest.ProtoReflect.Descriptor instead.
func (*GetNameRequest) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{3}
}

func (x *GetNameRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Name `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetNameResponse) Reset() {
	*x = GetNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameResponse) ProtoMessage() {}

func (x *GetNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameResponse.ProtoReflect.Descriptor instead.
func (*GetNameResponse) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{4}
}

func (x *GetNameResponse) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

type UpdateNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *Name `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *UpdateNameRequest) Reset() {
	*x = UpdateNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameRequest) ProtoMessage() {}

func (x *UpdateNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameRequest.ProtoReflect.Descriptor instead.
func (*UpdateNameRequest) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNameRequest) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

type UpdateNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateNameResponse) Reset() {
	*x = UpdateNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameResponse) ProtoMessage() {}

func (x *UpdateNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameResponse.ProtoReflect.Descriptor instead.
func (*UpdateNameResponse) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{6}
}

type DeleteNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeleteNameRequest) Reset() {
	*x = DeleteNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNameRequest) ProtoMessage() {}

func (x *DeleteNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNameRequest.ProtoReflect.Descriptor instead.
func (*DeleteNameRequest) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNameRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteNameResponse) Reset() {
	*x = DeleteNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNameResponse) ProtoMessage() {}

func (x *DeleteNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNameResponse.ProtoReflect.Descriptor instead.
func (*DeleteNameResponse) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{8}
}

type CompleteNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *CompleteNameRequest) Reset() {
	*x = CompleteNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteNameRequest) ProtoMessage() {}

func (x *CompleteNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteNameRequest.ProtoReflect.Descriptor instead.
func (*CompleteNameRequest) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteNameRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type CompleteNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteNameResponse) Reset() {
	*x = CompleteNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteNameResponse) ProtoMessage() {}

func (x *CompleteNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteNameResponse.ProtoReflect.Descriptor instead.
func (*CompleteNameResponse) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{10}
}

type GetAllDataNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllDataNameRequest) Reset() {
	*x = GetAllDataNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDataNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDataNameRequest) ProtoMessage() {}

func (x *GetAllDataNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDataNameRequest.ProtoReflect.Descriptor instead.
func (*GetAllDataNameRequest) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{11}
}

type GetAllDataNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []*Name `protobuf:"bytes,1,rep,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetAllDataNameResponse) Reset() {
	*x = GetAllDataNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDataNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDataNameResponse) ProtoMessage() {}

func (x *GetAllDataNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_free_go_gunk_v1_allData_all_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDataNameResponse.ProtoReflect.Descriptor instead.
func (*GetAllDataNameResponse) Descriptor() ([]byte, []int) {
	return file_free_go_gunk_v1_allData_all_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllDataNameResponse) GetName() []*Name {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_free_go_gunk_v1_allData_all_proto protoreflect.FileDescriptor

var file_free_go_gunk_v1_allData_all_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x67, 0x6f, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x12, 0x19, 0x0a, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x44, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x61, 0x6d,
	0x65, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08,
	0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x34, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x30, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28,
	0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x42, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x08,
	0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18,
	0x00, 0x22, 0x44, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4e,
	0x61, 0x6d, 0x65, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a,
	0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x1c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08,
	0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x33, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30, 0x00,
	0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x1c, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22, 0x35, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0a, 0x08, 0x00, 0x18,
	0x00, 0x28, 0x00, 0x30, 0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x1e, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x22,
	0x1f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00,
	0x22, 0x49, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0a, 0x08, 0x00, 0x18, 0x00, 0x28, 0x00, 0x30,
	0x00, 0x50, 0x00, 0x3a, 0x06, 0x08, 0x00, 0x10, 0x00, 0x18, 0x00, 0x32, 0x89, 0x04, 0x0a, 0x0b,
	0x4e, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x48,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x61, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02,
	0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x57,
	0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61,
	0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00,
	0x90, 0x02, 0x00, 0x28, 0x00, 0x30, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x06, 0x88, 0x02, 0x00, 0x90, 0x02, 0x00, 0x28, 0x00,
	0x30, 0x00, 0x1a, 0x03, 0x88, 0x02, 0x00, 0x42, 0x3a, 0x48, 0x01, 0x50, 0x00, 0x5a, 0x1f, 0x66,
	0x72, 0x65, 0x65, 0x5f, 0x67, 0x6f, 0x2f, 0x67, 0x75, 0x6e, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x3b, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x80, 0x01,
	0x00, 0x88, 0x01, 0x00, 0x90, 0x01, 0x00, 0xb8, 0x01, 0x00, 0xd8, 0x01, 0x00, 0xf8, 0x01, 0x01,
	0xd0, 0x02, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_free_go_gunk_v1_allData_all_proto_rawDescOnce sync.Once
	file_free_go_gunk_v1_allData_all_proto_rawDescData = file_free_go_gunk_v1_allData_all_proto_rawDesc
)

func file_free_go_gunk_v1_allData_all_proto_rawDescGZIP() []byte {
	file_free_go_gunk_v1_allData_all_proto_rawDescOnce.Do(func() {
		file_free_go_gunk_v1_allData_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_free_go_gunk_v1_allData_all_proto_rawDescData)
	})
	return file_free_go_gunk_v1_allData_all_proto_rawDescData
}

var file_free_go_gunk_v1_allData_all_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_free_go_gunk_v1_allData_all_proto_goTypes = []interface{}{
	(*Name)(nil),                   // 0: allData.Name
	(*CreateNameRequest)(nil),      // 1: allData.CreateNameRequest
	(*CreateNameResponse)(nil),     // 2: allData.CreateNameResponse
	(*GetNameRequest)(nil),         // 3: allData.GetNameRequest
	(*GetNameResponse)(nil),        // 4: allData.GetNameResponse
	(*UpdateNameRequest)(nil),      // 5: allData.UpdateNameRequest
	(*UpdateNameResponse)(nil),     // 6: allData.UpdateNameResponse
	(*DeleteNameRequest)(nil),      // 7: allData.DeleteNameRequest
	(*DeleteNameResponse)(nil),     // 8: allData.DeleteNameResponse
	(*CompleteNameRequest)(nil),    // 9: allData.CompleteNameRequest
	(*CompleteNameResponse)(nil),   // 10: allData.CompleteNameResponse
	(*GetAllDataNameRequest)(nil),  // 11: allData.GetAllDataNameRequest
	(*GetAllDataNameResponse)(nil), // 12: allData.GetAllDataNameResponse
}
var file_free_go_gunk_v1_allData_all_proto_depIdxs = []int32{
	0,  // 0: allData.CreateNameRequest.Name:type_name -> allData.Name
	0,  // 1: allData.GetNameResponse.Name:type_name -> allData.Name
	0,  // 2: allData.UpdateNameRequest.Name:type_name -> allData.Name
	0,  // 3: allData.GetAllDataNameResponse.Name:type_name -> allData.Name
	1,  // 4: allData.NameService.CreateName:input_type -> allData.CreateNameRequest
	3,  // 5: allData.NameService.GetName:input_type -> allData.GetNameRequest
	5,  // 6: allData.NameService.UpdateName:input_type -> allData.UpdateNameRequest
	7,  // 7: allData.NameService.DeleteName:input_type -> allData.DeleteNameRequest
	9,  // 8: allData.NameService.CompleteName:input_type -> allData.CompleteNameRequest
	11, // 9: allData.NameService.GetAllName:input_type -> allData.GetAllDataNameRequest
	2,  // 10: allData.NameService.CreateName:output_type -> allData.CreateNameResponse
	4,  // 11: allData.NameService.GetName:output_type -> allData.GetNameResponse
	6,  // 12: allData.NameService.UpdateName:output_type -> allData.UpdateNameResponse
	8,  // 13: allData.NameService.DeleteName:output_type -> allData.DeleteNameResponse
	10, // 14: allData.NameService.CompleteName:output_type -> allData.CompleteNameResponse
	12, // 15: allData.NameService.GetAllName:output_type -> allData.GetAllDataNameResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_free_go_gunk_v1_allData_all_proto_init() }
func file_free_go_gunk_v1_allData_all_proto_init() {
	if File_free_go_gunk_v1_allData_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_free_go_gunk_v1_allData_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDataNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_free_go_gunk_v1_allData_all_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDataNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_free_go_gunk_v1_allData_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_free_go_gunk_v1_allData_all_proto_goTypes,
		DependencyIndexes: file_free_go_gunk_v1_allData_all_proto_depIdxs,
		MessageInfos:      file_free_go_gunk_v1_allData_all_proto_msgTypes,
	}.Build()
	File_free_go_gunk_v1_allData_all_proto = out.File
	file_free_go_gunk_v1_allData_all_proto_rawDesc = nil
	file_free_go_gunk_v1_allData_all_proto_goTypes = nil
	file_free_go_gunk_v1_allData_all_proto_depIdxs = nil
}
