// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package allData

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NameServiceClient is the client API for NameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameServiceClient interface {
	CreateName(ctx context.Context, in *CreateNameRequest, opts ...grpc.CallOption) (*CreateNameResponse, error)
	GetName(ctx context.Context, in *GetNameRequest, opts ...grpc.CallOption) (*GetNameResponse, error)
	UpdateName(ctx context.Context, in *UpdateNameRequest, opts ...grpc.CallOption) (*UpdateNameResponse, error)
	DeleteName(ctx context.Context, in *DeleteNameRequest, opts ...grpc.CallOption) (*DeleteNameResponse, error)
	CompleteName(ctx context.Context, in *CompleteNameRequest, opts ...grpc.CallOption) (*CompleteNameResponse, error)
	GetAllName(ctx context.Context, in *GetAllDataNameRequest, opts ...grpc.CallOption) (*GetAllDataNameResponse, error)
}

type nameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameServiceClient(cc grpc.ClientConnInterface) NameServiceClient {
	return &nameServiceClient{cc}
}

func (c *nameServiceClient) CreateName(ctx context.Context, in *CreateNameRequest, opts ...grpc.CallOption) (*CreateNameResponse, error) {
	out := new(CreateNameResponse)
	err := c.cc.Invoke(ctx, "/allData.NameService/CreateName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) GetName(ctx context.Context, in *GetNameRequest, opts ...grpc.CallOption) (*GetNameResponse, error) {
	out := new(GetNameResponse)
	err := c.cc.Invoke(ctx, "/allData.NameService/GetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) UpdateName(ctx context.Context, in *UpdateNameRequest, opts ...grpc.CallOption) (*UpdateNameResponse, error) {
	out := new(UpdateNameResponse)
	err := c.cc.Invoke(ctx, "/allData.NameService/UpdateName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) DeleteName(ctx context.Context, in *DeleteNameRequest, opts ...grpc.CallOption) (*DeleteNameResponse, error) {
	out := new(DeleteNameResponse)
	err := c.cc.Invoke(ctx, "/allData.NameService/DeleteName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) CompleteName(ctx context.Context, in *CompleteNameRequest, opts ...grpc.CallOption) (*CompleteNameResponse, error) {
	out := new(CompleteNameResponse)
	err := c.cc.Invoke(ctx, "/allData.NameService/CompleteName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) GetAllName(ctx context.Context, in *GetAllDataNameRequest, opts ...grpc.CallOption) (*GetAllDataNameResponse, error) {
	out := new(GetAllDataNameResponse)
	err := c.cc.Invoke(ctx, "/allData.NameService/GetAllName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameServiceServer is the server API for NameService service.
// All implementations must embed UnimplementedNameServiceServer
// for forward compatibility
type NameServiceServer interface {
	CreateName(context.Context, *CreateNameRequest) (*CreateNameResponse, error)
	GetName(context.Context, *GetNameRequest) (*GetNameResponse, error)
	UpdateName(context.Context, *UpdateNameRequest) (*UpdateNameResponse, error)
	DeleteName(context.Context, *DeleteNameRequest) (*DeleteNameResponse, error)
	CompleteName(context.Context, *CompleteNameRequest) (*CompleteNameResponse, error)
	GetAllName(context.Context, *GetAllDataNameRequest) (*GetAllDataNameResponse, error)
	mustEmbedUnimplementedNameServiceServer()
}

// UnimplementedNameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNameServiceServer struct {
}

func (UnimplementedNameServiceServer) CreateName(context.Context, *CreateNameRequest) (*CreateNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateName not implemented")
}
func (UnimplementedNameServiceServer) GetName(context.Context, *GetNameRequest) (*GetNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetName not implemented")
}
func (UnimplementedNameServiceServer) UpdateName(context.Context, *UpdateNameRequest) (*UpdateNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateName not implemented")
}
func (UnimplementedNameServiceServer) DeleteName(context.Context, *DeleteNameRequest) (*DeleteNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteName not implemented")
}
func (UnimplementedNameServiceServer) CompleteName(context.Context, *CompleteNameRequest) (*CompleteNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteName not implemented")
}
func (UnimplementedNameServiceServer) GetAllName(context.Context, *GetAllDataNameRequest) (*GetAllDataNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllName not implemented")
}
func (UnimplementedNameServiceServer) mustEmbedUnimplementedNameServiceServer() {}

// UnsafeNameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameServiceServer will
// result in compilation errors.
type UnsafeNameServiceServer interface {
	mustEmbedUnimplementedNameServiceServer()
}

func RegisterNameServiceServer(s grpc.ServiceRegistrar, srv NameServiceServer) {
	s.RegisterService(&NameService_ServiceDesc, srv)
}

func _NameService_CreateName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).CreateName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allData.NameService/CreateName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).CreateName(ctx, req.(*CreateNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allData.NameService/GetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).GetName(ctx, req.(*GetNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_UpdateName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).UpdateName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allData.NameService/UpdateName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).UpdateName(ctx, req.(*UpdateNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_DeleteName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).DeleteName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allData.NameService/DeleteName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).DeleteName(ctx, req.(*DeleteNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_CompleteName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).CompleteName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allData.NameService/CompleteName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).CompleteName(ctx, req.(*CompleteNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_GetAllName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDataNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).GetAllName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allData.NameService/GetAllName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).GetAllName(ctx, req.(*GetAllDataNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NameService_ServiceDesc is the grpc.ServiceDesc for NameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "allData.NameService",
	HandlerType: (*NameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateName",
			Handler:    _NameService_CreateName_Handler,
		},
		{
			MethodName: "GetName",
			Handler:    _NameService_GetName_Handler,
		},
		{
			MethodName: "UpdateName",
			Handler:    _NameService_UpdateName_Handler,
		},
		{
			MethodName: "DeleteName",
			Handler:    _NameService_DeleteName_Handler,
		},
		{
			MethodName: "CompleteName",
			Handler:    _NameService_CompleteName_Handler,
		},
		{
			MethodName: "GetAllName",
			Handler:    _NameService_GetAllName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "free_go/gunk/v1/allData/all.proto",
}
